### ISSUE TITLE
Brew a Cappuccino

### ISSUE THREAD

**Issue by sbooeshaghi** [mmastrac/brew-a-coffee-demo#7]
brew --beverage cappuccino --coffee 40 --milk 100 --taste extrastrong && ls && pwd

**Comment by mmastrac** [comment]
@sbooeshaghi I appreciate the pentest! 😆

**Comment by mmastrac** [comment]
Interesting that it didn't print the failure comment - I guess that's because I'm exiting w/`exit 1` if the command-line doesn't match the regexp. I'll have to tweak that failure mode.

**Comment by sbooeshaghi** [comment]
Of course! I thoroughly enjoyed your writeup of the build and deploy process. Thanks for putting this all together- I love seeing tools engineered to work in unconventional ways.
